"""initial schema

Revision ID: 1cc00dc50a9c
Revises: 
Create Date: 2025-11-24 14:32:25.911472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc00dc50a9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commentary_id', sa.String(length=100), nullable=False, comment='External commentary ID'),
    sa.Column('match_id', sa.String(length=50), nullable=False, comment='External match ID'),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True, comment='WICKET, FOUR, SIX, BALL, etc.'),
    sa.Column('ball_number', sa.Integer(), nullable=True),
    sa.Column('over_number', sa.Float(), nullable=True),
    sa.Column('innings_id', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('wickets', sa.Integer(), nullable=True),
    sa.Column('batsman', sa.String(length=200), nullable=True),
    sa.Column('bowler', sa.String(length=200), nullable=True),
    sa.Column('batting_team_name', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When the event occurred'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='Additional commentary metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commentary_created', 'commentaries', ['created_at'], unique=False)
    op.create_index('idx_commentary_event_type', 'commentaries', ['event_type'], unique=False)
    op.create_index('idx_commentary_match_timestamp', 'commentaries', ['match_id', 'timestamp'], unique=False)
    op.create_index('idx_commentary_over_ball', 'commentaries', ['over_number', 'ball_number'], unique=False)
    op.create_index(op.f('ix_commentaries_ball_number'), 'commentaries', ['ball_number'], unique=False)
    op.create_index(op.f('ix_commentaries_commentary_id'), 'commentaries', ['commentary_id'], unique=True)
    op.create_index(op.f('ix_commentaries_event_type'), 'commentaries', ['event_type'], unique=False)
    op.create_index(op.f('ix_commentaries_innings_id'), 'commentaries', ['innings_id'], unique=False)
    op.create_index(op.f('ix_commentaries_match_id'), 'commentaries', ['match_id'], unique=False)
    op.create_index(op.f('ix_commentaries_over_number'), 'commentaries', ['over_number'], unique=False)
    op.create_index(op.f('ix_commentaries_timestamp'), 'commentaries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commentaries_timestamp'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_over_number'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_match_id'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_innings_id'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_event_type'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_commentary_id'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_ball_number'), table_name='commentaries')
    op.drop_index('idx_commentary_over_ball', table_name='commentaries')
    op.drop_index('idx_commentary_match_timestamp', table_name='commentaries')
    op.drop_index('idx_commentary_event_type', table_name='commentaries')
    op.drop_index('idx_commentary_created', table_name='commentaries')
    op.drop_table('commentaries')
    # ### end Alembic commands ###
