"""remove commentary_id

Revision ID: d29522fe52ba
Revises: 1cc00dc50a9c
Create Date: 2025-11-24 15:15:00.034369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29522fe52ba'
down_revision: Union[str, None] = '1cc00dc50a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commentaries_commentary_id', table_name='commentaries')
    op.drop_index('idx_commentary_match_timestamp', table_name='commentaries')
    op.create_index('idx_commentary_match_timestamp', 'commentaries', ['match_id', 'timestamp'], unique=True)
    op.drop_column('commentaries', 'commentary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentaries', sa.Column('commentary_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='External commentary ID'))
    op.drop_index('idx_commentary_match_timestamp', table_name='commentaries')
    op.create_index('idx_commentary_match_timestamp', 'commentaries', ['match_id', 'timestamp'], unique=False)
    op.create_index('ix_commentaries_commentary_id', 'commentaries', ['commentary_id'], unique=True)
    # ### end Alembic commands ###
